CREATE VIEW suiviReseau AS
   SELECT S.MOMENT, S.ACTION, S.CODERESEAU, R.NOM FROM RESEAU R INNER JOIN SUIVI_RESEAU S
   ON R.CODE = S.CODERESEAU
   WHERE S.NOJOUEUR = NULL
   ORDER BY S.MOMENT ASC;
   
CREATE VIEW suiviReseauJoueur AS
   SELECT S.MOMENT, S.ACTION, S.CODERESEAU, J.SURNOM FROM JOUEUR J INNER JOIN SUIVI_RESEAU S
   ON J.NOJOUEUR = S.NOJOUEUR
   WHERE S.NOJOUEUR != NULL
   ORDER BY S.MOMENT ASC;
   
CREATE VIEW suiviAmitieInvitation AS
   SELECT S.MOMENT, J.SURNOM, J.NOJOUEUR, S.NOJOUEURINVITE, S.DATESUIVI, S.CODESTATUT FROM JOUEUR J INNER JOIN SUIVI_AMITIE S
   ON J.NOJOUEUR = S.NOJOUEURINVITANT;