CREATE OR REPLACE TRIGGER Suivi_Reseau_TRG
    AFTER INSERT OR UPDATE
    ON RESEAU
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO SUIVI_RESEAU(MOMENT, CODERESEAU, DATESUIVI, ACTION)
        VALUES(CURRENT_TIMESTAMP(), :NEW.CODE, SYSDATE(), 'CRE');
    ELSIF UPDATING THEN
        IF (:NEW.ACTIF = '1') THEN
            INSERT INTO SUIVI_RESEAU(MOMENT, CODERESEAU, DATESUIVI, ACTION)
            VALUES(CURRENT_TIMESTAMP(), :NEW.CODE, SYSDATE(), 'ACT');
        ELSE
            INSERT INTO SUIVI_RESEAU(MOMENT, CODERESEAU, DATESUIVI, ACTION)
            VALUES(CURRENT_TIMESTAMP(), :NEW.CODE, SYSDATE(), 'DES');
        END IF;
    END IF;
END;