CREATE OR REPLACE TRIGGER Suivi_Ami_TRG
    AFTER INSERT OR DELETE OR UPDATE
    ON AMI
    FOR EACH ROW
BEGIN
    IF INSERTING OR UPDATING THEN
        INSERT INTO SUIVI_AMITIE(NOJOUEURINVITANT, NOJOUEURINVITE, DATESUIVI, CODESTATUT)
        VALUES(:NEW.NOJOUEURINVITANT, :NEW.NOJOUEURINVITE, SYSDATE(), :NEW.CODESTATUT);
    ELSIF DELETING THEN
        INSERT INTO SUIVI_AMITIE(NOJOUEURINVITANT, NOJOUEURINVITE, DATESUIVI, CODESTATUT)
        VALUES(:OLD.NOJOUEURINVITANT, :OLD.NOJOUEURINVITE, SYSDATE(), :OLD.CODESTATUT);
    END IF;
END;