CREATE OR REPLACE TRIGGER Suivi_Abonnement_Reseau_TRG
    AFTER INSERT OR DELETE
    ON ABONNEMENT_RESEAU
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO SUIVI_RESEAU(CODERESEAU, DATESUIVI, ACTION)
        VALUES(:NEW.CODERESEAU, SYSDATE(), 'ABO');
    ELSIF DELETING THEN
        INSERT INTO SUIVI_RESEAU(CODERESEAU, DATESUIVI, ACTION)
        VALUES(:OLD.CODERESEAU, SYSDATE(), 'DSA');
    END IF;
END;