CREATE OR REPLACE TRIGGER Suivi_Abonnement_Reseau_TRG
    AFTER INSERT OR DELETE
    ON ABONNEMENT_RESEAU
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO SUIVI_RESEAU(CODERESEAU, DATESUIVI, ACTION, NOJOUEUR)
        VALUES(:NEW.CODERESEAU, SYSDATE(), 'ABO', :NEW.NOJOUEUR);
    ELSIF DELETING THEN
        INSERT INTO SUIVI_RESEAU(CODERESEAU, DATESUIVI, ACTION, NOJOUEUR)
        VALUES(:OLD.CODERESEAU, SYSDATE(), 'DSA', :OLD.NOJOUEUR);
    END IF;
END;