CREATE OR REPLACE FUNCTION jeuLePlusPopulaire(code_esrb IN CHAR) RETURN VARCHAR2 AS

	nom_jeu_plus_populaire JEU.NOM%TYPE;
    
BEGIN
	SELECT NOM
    INTO nom_jeu_plus_populaire
    FROM JEU
    WHERE IDJEU =
    (SELECT IDJEU
    FROM CONTENU
    WHERE IDCONTENU =
    (SELECT IDCONTENU
    FROM (SELECT IDCONTENU, COUNT(*) as nb
    FROM CONTENU_POSSEDE
    WHERE IDCONTENU IN (SELECT IDCONTENU FROM CONTENU WHERE IDJEU IN (SELECT IDJEU FROM JEU WHERE CODEESRB = code_esrb) AND TYPECONTENU = 'J')
    AND NOJOUEUR IN (SELECT NOJOUEUR FROM JOUEUR WHERE ACTIF = '1')
    AND NOJOUEUR IN (SELECT NOJOUEUR FROM SUCCES_REALISE WHERE IDCONTENU = IDCONTENU)
    GROUP BY IDCONTENU
    ORDER BY nb)
    WHERE rownum = 1));

	RETURN nom_jeu_plus_populaire;
    
END jeuLePlusPopulaire;